# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_call:

jobs:
  build:
    
    uses: Abaddax/workflows/.github/workflows/dotnet.build_and_test.yml@master
