# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish

on:
  push:
    branches: [ "master" ]
    paths:
      - "**/*.csproj"
  workflow_dispatch:

env:
  CSPROJ_PATH: Abaddax.Utilities/Abaddax.Utilities.csproj

jobs:

  check_version:
    
    uses: Abaddax/workflows/.github/workflows/dotnet.check_version.yml@master
    with:
      CSPROJ_PATH: ${{ env.CSPROJ_PATH }}

  ci:
    
    needs: [check_version]
    if: needs.check_version.outputs.version_changed == 'true'
    uses: ./.github/workflows/ci.yml
  
  publish:
  
    needs: [check_version, ci]
    if: needs.check_version.outputs.version_changed == 'true'
    uses: Abaddax/workflows/.github/workflows/dotnet.publish_nuget.yml@master
    with:
      CSPROJ_PATH: ${{ env.CSPROJ_PATH }}
    permissions:
      contents: write
    secrets:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
